### PR TITLE
[Nokia][sonic-platform] Update Nokia sonic-platform submodule for explicit sync to SSD when watchdog is known to be approaching

### PR DESCRIPTION
**Pull request by snider-nokia**
#### Why I did it

To ensure that write cache is flushed to SSD when SW has determined that a watchdog reset is approaching.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

When watchdog kicker script has determined that watchdog should no longer be kicked, due to degraded system health, explicitly and periodically issue sync commands until watchdog reset occurs.

#### How to verify it

This is difficult to verify without ad-hoc system modifications to simulate degraded system health.  This functionality has been tested here in our labs and works.

#### Which release branch to backport (provide reason below if selected)

This logic will be added/ported separately for master/202405 branch(es).

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [x] 202205

#### Description for the changelog
[Nokia][sonic-platform] Update Nokia sonic-platform submodule for explicit sync to SSD when watchdog is known to be approaching

### CODE REVIEW

**Comment by snider-nokia** [comment]
@judyjoseph @deepak-singhal0408 @vmittal-msft @arlakshm, Please merge and use this change for next pilot candidate image build (along with NDK 22.9.30).    NDK 22.9.30 and these changes do NOT NEED to be paired, however both these changes and NDK 22.9.30 are recommended for incorporation into next pilot candidate image build.

**Comment by judyjoseph** [comment]
@snider-nokia @jon-nokia  could you rebase this PR and the corresponding NDK PR

**Comment by jon-nokia** [comment]
> @snider-nokia @jon-nokia could you rebase this PR and the corresponding NDK PR

https://github.com/sonic-net/sonic-buildimage-msft/pull/426 has been rebased.

**Comment by snider-nokia** [comment]
This one is rebased now too.

**Comment by judyjoseph** [comment]
@snider-nokia Was going through the watchdog.sh, here below code line 145, is it intentional we echo this line into log file only if $watchdog_fail ==  1, as we reset to 0 the first time we enter this if condition.
```
    if [[ $watchdog_fail -eq 1 ]]; then
        echo "enable watchdog kick" `date -u` >> $wd_init_log_file
        watchdog_fail=0
    fi
```

**Comment by snider-nokia** [comment]
> @snider-nokia Was going through the watchdog.sh, here below code line 145, is it intentional we echo this line into log file only if $watchdog_fail == 1, as we reset to 0 the first time we enter this if condition.
> 
> ```
>     if [[ $watchdog_fail -eq 1 ]]; then
>         echo "enable watchdog kick" `date -u` >> $wd_init_log_file
>         watchdog_fail=0
>     fi
> ```

Yes Judy, it is intentional.  This code handles the situation where $watchdog_fail was previously set to 1 because our health-check-ping-to-NDK did not succeed.  When that occurs, and if a subsequent health-check-ping-to-NDK then does succeed then this logic tells us that such a scenario occurred and also reenables kicking of the watchdog.   So, this logic is only handling/logging the case where we transitioned from unsuccessful health-check-ping-to-NDK back to successful health-check-ping-to-NDK.

**Review by judyjoseph — APPROVED** [review]

**Review by gechiang — APPROVED** [review]

**Pull request merged**
