### PR TITLE
22.9.32 

### PR DESCRIPTION
**Pull request by jon-nokia**
#### Why I did it
Call platform specific reboot when unable to reach CPM
Disable Tx when reboot is ungraceful
Ensure ASIC related thermal sensors are always added in proper order

##### Work item tracking
- Microsoft ADO **(number only)**:

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012
- [ ] 202106
- [ ] 202111
- [ ] 202205
- [ ] 202211

#### Tested branch (Please provide the tested image version)

- [ ] 
- [ ]

### CODE REVIEW

**Comment by mlok-nokia** [comment]
@judyjoseph @deepak-singhal0408  This PR is the new NDK for next 202205 image build

**Review by deepak-singhal0408 — APPROVED** [review]

**Comment by deepak-singhal0408** [comment]
@judyjoseph @gechiang can you please help merge this PR? We need to take this change for our next 202205 image. Thanks

**Comment by deepak-singhal0408** [comment]
MSFt ADO: 29979359

**Comment by gechiang** [comment]
> @judyjoseph @gechiang can you please help merge this PR? We need to take this change for our next 202205 image. Thanks

@BYGX-wcr for Viz

**Pull request merged**
